[build]
builder = "NIXPACKS"

[deploy]
# Головна команда старту контейнера
startCommand = "python main.py"

# Хелсчек — будемо пінгати бекенд
healthcheckPath = "/ping"
healthcheckTimeout = 120

# Щоб перезапускався, якщо впаде
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 5
